import type { DB } from './types'
import { enDias } from './utils'

/**
 * DATOS REALES — WorkSpace OS (instanciación inicial)
 * Fuentes: GitLab local (sales-ai-platform/wibsite), GitHub (joseRobertoQuiroga),
 * Notion (documentación maestra) y horarios universitarios del usuario.
 * Actualizado: 2026-09-07
 */
export const seedDB = (): DB => ({
  areas: [
    { id: 'universidad', nombre: 'Universidad', icono: 'school', color: 'area-univ' },
    { id: 'freelance', nombre: 'Freelance', icono: 'business_center', color: 'area-freelance' },
    { id: 'emprendimiento', nombre: 'Emprendimiento', icono: 'lightbulb', color: 'area-emprende' },
    { id: 'personal', nombre: 'Personal', icono: 'favorite', color: 'area-personal' },
  ],
  plantillas: [
    { id: 'tpl-nota-rapida', nombre: 'Nota rápida', icono: 'bolt', color: 'area-personal', area_id: null, es_sistema: true, campos: [] },
    { id: 'tpl-materia', nombre: 'Materia universitaria', icono: 'school', color: 'area-univ', area_id: 'universidad', es_sistema: true, campos: [{ campo: 'Docente', tipo: 'texto' }, { campo: 'Semestre', tipo: 'texto' }, { campo: 'Horario', tipo: 'texto' }] },
    { id: 'tpl-proyecto', nombre: 'Proyecto', icono: 'rocket_launch', color: 'area-emprende', area_id: 'emprendimiento', es_sistema: true, campos: [{ campo: 'Stack', tipo: 'texto' }, { campo: 'Repositorio', tipo: 'texto' }] },
    { id: 'tpl-cliente', nombre: 'Cliente', icono: 'handshake', color: 'area-freelance', area_id: 'freelance', es_sistema: true, campos: [{ campo: 'Contacto', tipo: 'texto' }, { campo: 'Estado relación', tipo: 'select', opciones: ['Prospecto', 'Activo', 'Inactivo'] }] },
    { id: 'tpl-adr', nombre: 'Decisión técnica (ADR)', icono: 'account_tree', color: 'area-emprende', area_id: null, es_sistema: true, campos: [{ campo: 'Contexto', tipo: 'texto' }, { campo: 'Alternativas', tipo: 'texto' }, { campo: 'Consecuencias', tipo: 'texto' }] },
  ],

  // ===================== UNIVERSIDAD =====================
  materias: [
    {
      id: 'mat-ingles',
      nombre: 'Inglés Básico',
      semestre: 'Actual',
      docente: '—',
      horario: 'Lun 7:45-9:15 · Vie 7:45-9:15',
      bloques: [
        { dia: 1, inicio: '07:45', fin: '09:15' },
        { dia: 5, inicio: '07:45', fin: '09:15' },
      ],
      creditos: 3,
      color: 'area-univ',
      unidades: [],
    },
    {
      id: 'mat-modelamiento-bd',
      nombre: 'Modelamiento de Base de Datos',
      semestre: 'Actual',
      docente: '—',
      horario: 'Lun 9:15-10:30 · Jue 9:15-11:30',
      bloques: [
        { dia: 1, inicio: '09:15', fin: '10:30' },
        { dia: 4, inicio: '09:15', fin: '11:30' },
      ],
      creditos: 4,
      color: 'area-univ',
      unidades: [
        {
          id: 'uni-mbd-1',
          titulo: 'Unidad 1 · Modelo Entidad-Relación',
          tema: 'Diseño conceptual de bases de datos',
          temas: [
            {
              id: 'tema-mbd-1-1',
              titulo: 'Entidades, atributos y relaciones',
              contexto: 'Fundamentos del modelo E-R: entidades fuertes/débiles, atributos simples/compuestos/multivaluados, cardinalidad y participación.',
              apuntes: 'Una **entidad** representa un objeto del mundo real. Los **atributos** describen sus propiedades. La **cardinalidad** define cuántas instancias se relacionan (1:1, 1:N, N:M).\n\n- Entidad fuerte: tiene existencia propia.\n- Entidad débil: depende de otra.\n- Clave primaria identifica cada instancia.',
              pizarra: [
                { id: 'pz-mbd-1-1', titulo: 'Ejemplo E-R', texto: 'CLIENTE (id, nombre) ---1:N--- PEDIDO (id, fecha)', color: 'rgb(var(--area-univ))', x: 60, y: 60, ancho: 260, alto: 90 },
              ],
              creado_en: new Date().toISOString(),
              actualizado_en: new Date().toISOString(),
            },
            {
              id: 'tema-mbd-1-2',
              titulo: 'Normalización 1FN · 2FN · 3FN',
              contexto: 'Reglas para eliminar redundancia: cada celda atómica, dependencia total y dependencia transitiva.',
              apuntes: '**1FN:** valores atómicos. **2FN:** sin dependencias parciales. **3FN:** sin dependencias transitivas.\n\nEjercicio: descomponer una tabla con datos repetidos en formas normales.',
              pizarra: [],
              creado_en: new Date().toISOString(),
              actualizado_en: new Date().toISOString(),
            },
          ],
          creado_en: new Date().toISOString(),
        },
        {
          id: 'uni-mbd-2',
          titulo: 'Unidad 2 · SQL y consultas',
          tema: 'Lenguaje de consulta estructurado',
          temas: [
            {
              id: 'tema-mbd-2-1',
              titulo: 'DDL y DML básico',
              contexto: 'CREATE/ALTER/DROP, INSERT/UPDATE/DELETE y SELECT con JOINs.',
              apuntes: '```sql\nSELECT p.nombre, COUNT(o.id)\nFROM pedidos o\nJOIN clientes p ON p.id = o.cliente_id\nGROUP BY p.nombre;\n```',
              pizarra: [],
              creado_en: new Date().toISOString(),
              actualizado_en: new Date().toISOString(),
            },
          ],
          creado_en: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'mat-poo',
      nombre: 'Programación Orientada a Objetos',
      semestre: 'Actual',
      docente: '—',
      horario: 'Mar 7:45-10:30 · Jue 7:45-9:15',
      bloques: [
        { dia: 2, inicio: '07:45', fin: '10:30' },
        { dia: 4, inicio: '07:45', fin: '09:15' },
      ],
      creditos: 4,
      color: 'area-univ',
      unidades: [
        {
          id: 'uni-poo-1',
          titulo: 'Unidad 1 · Clases y objetos',
          tema: 'Fundamentos de la POO',
          temas: [
            {
              id: 'tema-poo-1-1',
              titulo: 'Abstracción y encapsulamiento',
              contexto: 'Modelar entidades como clases; ocultar estado interno mediante modificadores de acceso.',
              apuntes: 'La **clase** es una plantilla; el **objeto** una instancia. `private` oculta el estado, `public` expone la interfaz.',
              pizarra: [
                { id: 'pz-poo-1-1', titulo: 'Diagrama de clase', texto: 'CuentaBancaria\n- saldo: decimal\n+ depositar(monto)\n+ retirar(monto)', color: 'rgb(var(--accent))', x: 60, y: 60, ancho: 240, alto: 120 },
              ],
              creado_en: new Date().toISOString(),
              actualizado_en: new Date().toISOString(),
            },
          ],
          creado_en: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'mat-matematica-discreta',
      nombre: 'Matemática Discreta',
      semestre: 'Actual',
      docente: '—',
      horario: 'Mié 7:45-9:15 · Vie 9:15-11:30',
      bloques: [
        { dia: 3, inicio: '07:45', fin: '09:15' },
        { dia: 5, inicio: '09:15', fin: '11:30' },
      ],
      creditos: 4,
      color: 'area-univ',
      unidades: [
        {
          id: 'uni-md-1',
          titulo: 'Unidad 1 · Lógica proposicional',
          tema: 'Verdad, conectivos y tablas',
          temas: [
            {
              id: 'tema-md-1-1',
              titulo: 'Conectivos lógicos',
              contexto: 'Negación, conjunción, disyunción, implicación y bicondicional.',
              apuntes: '| p | q | p→q |\n|---|---|-----|\n| V | V |  V  |\n| V | F |  F  |\n\nLa implicación solo es falsa cuando el antecedente es verdadero y el consecuente falso.',
              pizarra: [],
              creado_en: new Date().toISOString(),
              actualizado_en: new Date().toISOString(),
            },
          ],
          creado_en: new Date().toISOString(),
        },
      ],
    },
    {
      id: 'mat-administracion-negocios',
      nombre: 'Administración de Negocios',
      semestre: 'Actual',
      docente: '—',
      horario: 'Mié 9:15-12:15',
      bloques: [{ dia: 3, inicio: '09:15', fin: '12:15' }],
      creditos: 3,
      color: 'area-univ',
      unidades: [],
    },
    {
      id: 'mat-cna',
      nombre: 'CNA 1',
      semestre: 'Actual',
      docente: '—',
      horario: 'Sáb 7:45-11:30',
      bloques: [{ dia: 6, inicio: '07:45', fin: '11:30' }],
      creditos: 3,
      color: 'area-univ',
      unidades: [],
    },
  ],

  // ===================== PROYECTOS =====================
  proyectos: [
    // --- Emprendimiento / proyectos personales ---
    {
      id: 'proy-wibsite',
      nombre: 'Wibsite — Plataforma de Mensajería Omnicanal',
      area_id: 'emprendimiento',
      tipo: 'Producto propio',
      estado: 'activo',
      prioridad: 'alta',
      destacado: true,
      fecha_inicio: null,
      fecha_limite: null,
      stack: ['Docker', 'Node.js', 'PostgreSQL', 'Redis', 'n8n', 'Dify', 'Twenty CRM', 'Chatwoot', 'Elastic Stack'],
      descripcion: 'SaaS de mensajería omnicanal con IA: campañas por WhatsApp/Messenger/TikTok/SMS/Email, clasificación automática de leads, asistente virtual 24/7 y CRM integrado (Twenty). Fase 1 en progreso (~70%).',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'proy-ecommerce',
      nombre: 'E-commerce Dropshipping con IA',
      area_id: 'emprendimiento',
      tipo: 'Producto propio',
      estado: 'idea',
      prioridad: 'media',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: ['Python', 'FastAPI', 'Crawl4AI', 'pgvector', 'Clean Architecture'],
      descripcion: 'E-commerce dropshipping con scraping IA y chatbot híbrido SQL + RAG. En refinamiento conceptual (v0.1-arquitectura).',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'proy-dogshipping',
      nombre: 'Dogshipping Multicommer',
      area_id: 'emprendimiento',
      tipo: 'Producto propio',
      estado: 'idea',
      prioridad: 'media',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: [],
      descripcion: 'Plataforma multicomercio (dogshipping). En etapa conceptual y refinamiento.',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'proy-casa-domotica',
      nombre: 'Casa Domótica',
      area_id: 'emprendimiento',
      tipo: 'Producto propio',
      estado: 'idea',
      prioridad: 'baja',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: [],
      descripcion: 'Automatización y domótica del hogar. En etapa conceptual.',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    // --- Freelance (GitHub) ---
    {
      id: 'proy-ticketero',
      nombre: 'Sistema Ticketero',
      area_id: 'freelance',
      tipo: 'Cliente freelance',
      estado: 'activo',
      prioridad: 'media',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: ['.NET 8', 'Flutter', 'SQL Server 2022', 'Redis', 'Docker', 'SignalR'],
      descripcion: 'Sistema integral de gestión de turnos para atención al cliente: toma de tickets en kiosko físico/virtual, atención en tiempo real con WebSockets, monitor de puestos, panel de administración y dashboard interactivo.',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'proy-sistema-prestamos',
      nombre: 'Sistema de Gestión de Préstamos',
      area_id: 'freelance',
      tipo: 'Cliente freelance',
      estado: 'activo',
      prioridad: 'media',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: ['Flutter', 'SQLite'],
      descripcion: 'Aplicación de escritorio (Windows) para gestión de préstamos y control de caja: clientes, tablas de amortización, pagos en cascada, mora, cajas/cuentas y reportes. Arquitectura limpia SOLID, modo oscuro.',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'proy-billar',
      nombre: 'BillarSistem',
      area_id: 'freelance',
      tipo: 'Cliente freelance',
      estado: 'activo',
      prioridad: 'media',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: ['Flutter', 'Dart'],
      descripcion: 'Sistema de gestión de billar. Arquitectura local-first con sincronización híbrida. Documentación de diseño completa (v1.0-espec).',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'proy-fairplay',
      nombre: 'FairPlay Anti-Robo',
      area_id: 'freelance',
      tipo: 'Cliente freelance',
      estado: 'activo',
      prioridad: 'media',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: ['Python', 'customtkinter', 'ZKTeco U2000F'],
      descripcion: 'Sistema antirrobo UHF RFID. Demo MVP funcional con modo simulación y modo real (v0.1-demo).',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'proy-avatar13',
      nombre: 'Avatar-13',
      area_id: 'freelance',
      tipo: 'Cliente freelance',
      estado: 'activo',
      prioridad: 'baja',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: ['MediaPipe', 'Unity', 'UniVRM', 'Python', 'TypeScript'],
      descripcion: 'Captura de movimiento de avatar en tiempo real mediante visión artificial. 100% local, privado y seguro. En desarrollo activo (v0.2.0).',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'proy-gestor-proyectos',
      nombre: 'Gestor Proyectos (AI Governance)',
      area_id: 'freelance',
      tipo: 'Cliente freelance',
      estado: 'activo',
      prioridad: 'media',
      destacado: false,
      fecha_inicio: null,
      fecha_limite: null,
      stack: ['Fastify', 'React', 'TypeScript'],
      descripcion: 'Plataforma de gobernanza activa y auditoría técnica para proyectos asistidos por IA: Digital Twin, Health Baseline (6 dimensiones), ADRs, panel de actividad en tiempo real (v0.1-alpha).',
      cliente_id: null,
      creado_en: new Date().toISOString(),
    },
  ],

  // ===================== TAREAS =====================
  tareas: [
    // --- Hábitos diarios (vida personal) ---
    ...[
      { id: 'hab-ejercicio', titulo: 'Ejercicio 15-20 min', etiqueta: ['habito', 'salud'] },
      { id: 'hab-lectura', titulo: 'Leer / investigar 2h diarias', etiqueta: ['habito', 'lectura'] },
    ].flatMap((h) =>
      Array.from({ length: 8 }, (_, i) => {
        const hecho = Math.random() > 0.3
        const fecha = enDias(i - 7)
        return {
          id: `${h.id}-${fecha}`,
          titulo: h.titulo,
          area_id: 'personal' as const,
          proyecto_id: null,
          estado: (hecho ? 'hecho' : 'por_hacer') as 'hecho' | 'por_hacer',
          prioridad: 'baja' as const,
          destacado: false,
          fecha_limite: fecha,
          notas: '',
          etiquetas: h.etiqueta,
          arrastrada: false,
          mi_dia: false,
          subtareas: [],
          recurrencia: 'diaria' as const,
          cerrada_en: hecho ? new Date(Date.now() - (7 - i) * 86400000).toISOString() : null,
          creado_en: new Date().toISOString(),
        }
      })
    ),
    // --- Próximos pasos Wibsite (del estado ejecutivo) ---
    {
      id: 'tar-chatwoot',
      titulo: 'Diagnosticar Chatwoot (reinicio continuo)',
      area_id: 'emprendimiento',
      proyecto_id: 'proy-wibsite',
      estado: 'por_hacer',
      prioridad: 'alta',
      destacado: true,
      fecha_limite: null,
      notas: 'Revisar logs del contenedor para solucionar el reinicio continuo. Fuente: ESTADO-EJECUTIVO.md · P1.',
      etiquetas: ['wibsite', 'infra'],
      arrastrada: false,
      mi_dia: false,
      subtareas: [],
      recurrencia: null,
      cerrada_en: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'tar-n8n',
      titulo: 'Probar workflows n8n en UI',
      area_id: 'emprendimiento',
      proyecto_id: 'proy-wibsite',
      estado: 'por_hacer',
      prioridad: 'media',
      destacado: false,
      fecha_limite: null,
      notas: 'Verificar que los workflows están visibles y ejecutan. Fuente: ESTADO-EJECUTIVO · próximo paso 2.',
      etiquetas: ['wibsite', 'n8n'],
      arrastrada: false,
      mi_dia: false,
      subtareas: [],
      recurrencia: null,
      cerrada_en: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'tar-dify',
      titulo: 'Verificar login y acceso a Dify',
      area_id: 'emprendimiento',
      proyecto_id: 'proy-wibsite',
      estado: 'por_hacer',
      prioridad: 'media',
      destacado: false,
      fecha_limite: null,
      notas: 'Confirmar credenciales admin del panel de agentes. Fuente: ESTADO-EJECUTIVO · próximo paso 3.',
      etiquetas: ['wibsite', 'dify'],
      arrastrada: false,
      mi_dia: false,
      subtareas: [],
      recurrencia: null,
      cerrada_en: null,
      creado_en: new Date().toISOString(),
    },
    {
      id: 'tar-onboarding',
      titulo: 'Preparar documentación de onboarding',
      area_id: 'emprendimiento',
      proyecto_id: 'proy-wibsite',
      estado: 'por_hacer',
      prioridad: 'media',
      destacado: false,
      fecha_limite: null,
      notas: 'Para cuando lleguen credenciales Meta, poder encender todo rápidamente. Fuente: ESTADO-EJECUTIVO · próximo paso 4.',
      etiquetas: ['wibsite', 'docs'],
      arrastrada: false,
      mi_dia: false,
      subtareas: [],
      recurrencia: null,
      cerrada_en: null,
      creado_en: new Date().toISOString(),
    },
  ],

  // ===================== NOTAS (índice de documentación real) =====================
  notas: [
    {
      id: 'nota-wibsite-index',
      titulo: 'Wibsite · Índice de documentación (GitLab)',
      proyecto_id: 'proy-wibsite',
      area_id: 'emprendimiento',
      plantilla_id: 'tpl-nota-rapida',
      tipo: 'Guía',
      estado: 'publicado',
      contenido_md: '# Índice Wibsite (GitLab · sales-ai-platform/wibsite)\n\n- `wibsite/INDEX.md` — guía visual de la documentación (100+ docs).\n- `Avances/` — ESTADO-GENERAL, COMPONENTES, LOGROS, OBJETIVOS-PENDIENTES, ROADMAP, PROCEDIMIENTOS.\n- `docs/contextual/` — capa QUÉ/POR QUÉ (7 bloques CTX: infraestructura, objetivos, abstracción CRM/ERP, lógica vendedor, plantillas por rubro, lógica negocio, consolidación).\n- `docs/tecnica/` — capa CÓMO (TEC-01..06, incl. TEC-06 con 56 micro-fases).\n- `docs/maestro/` — MAESTRO-FUNCIONALIDADES-CORE (68 entradas RAG).\n- Maestros estratégicos: BUSINESS, DATA, OPS, SECURITY, UI-UX, ROADMAP-MULTI-AGENT-MEMORY-CONTEXT.\n- `docs/context/` — fichas por módulo (Chatwoot, Dify, n8n, Twenty, helper, campaigns).\n- `docs/rag/` — datos compactos para IA (endpoints, credenciales, env, dependencias).',
      resumen: 'Mapa de navegación de la documentación oficial de Wibsite en GitLab.',
      etiquetas: ['wibsite', 'documentación', 'gitlab'],
      creado_en: new Date().toISOString(),
      actualizado_en: new Date().toISOString(),
    },
    {
      id: 'nota-wibsite-estado',
      titulo: 'Wibsite · Estado ejecutivo (jul 2026)',
      proyecto_id: 'proy-wibsite',
      area_id: 'emprendimiento',
      plantilla_id: 'tpl-nota-rapida',
      tipo: 'Nota de reunión',
      estado: 'publicado',
      contenido_md: '# Estado Wibsite\n- Fase 0.5 — Plataforma Base (70% de avance).\n- 10+ servicios Docker operativos: PostgreSQL, Redis, Weaviate, n8n, Dify, Twenty, Chatwoot, Nginx, Elastic Stack.\n- Listo: gestión de campañas multicanal, 11 plantillas, importación Excel/CSV, CRM Twenty (10 campos custom, 12 leads), motor de clasificación de leads (Hot/Warm/Cold), dashboard de monitoreo, 2 workflows n8n, base multi-tenant.\n- Bloqueado por: credenciales Meta/WhatsApp y créditos de IA (xAI/OpenAI).\n- Cobertura: infra 80% · hub 90% · API 95% · dashboard 95% · CRM 90% · n8n 60% · Dify 40% · Chatwoot 0% (caído) · WhatsApp 0% · scoring 90% · docs 100%.',
      resumen: 'Estado ejecutivo y cobertura de módulos del proyecto Wibsite.',
      etiquetas: ['wibsite', 'estado'],
      creado_en: new Date().toISOString(),
      actualizado_en: new Date().toISOString(),
    },
  ],

  clientes: [],
  ideas: [],
  eventos: [],
  asistencias: [],
  pomodoroLog: [],

  // ===================== FICHAS =====================
  fichas: [
    {
      id: 'ficha-wibsite',
      titulo: 'Wibsite — Plataforma de Mensajería Omnicanal',
      subtitulo: 'Ficha Maestra · SaaS con IA · Fase 1 en progreso (70%)',
      tipo: 'proyecto',
      entidad_id: 'proy-wibsite',
      area_id: 'emprendimiento',
      estado: 'EN DESARROLLO · FASE 1 (70%)',
      estado_color: 'area-emprende',
      propiedades: [
        { etiqueta: 'Fuente de verdad', valor: 'GitLab local · sales-ai-platform/wibsite', icono: 'gitlab' },
        { etiqueta: 'Stack', valor: '20 servicios Docker · Node · PG · Redis · n8n · Dify · Twenty · Chatwoot · Elastic', icono: 'layers' },
        { etiqueta: 'Prioridad', valor: 'ALTA — único en pre-producción', icono: 'priority_high' },
        { etiqueta: 'Canales', valor: 'WhatsApp · Messenger · TikTok · SMS · Email', icono: 'campaign' },
        { etiqueta: 'Bloqueos', valor: 'Credenciales Meta + créditos IA (xAI/OpenAI)', icono: 'block' },
      ],
      secciones: [
        {
          id: 'sec-estado',
          titulo: 'Estado y cobertura de módulos',
          icono: 'monitor_heart',
          contenido: [
            'Fase 0 (Fundación) COMPLETADA. Fase 1 (WhatsApp + IA + Twenty CRM) EN PROGRESO 70%. Fases 2-7 (Frappe ERP, Lumi Sales Copilot, Pipeline IA, Producción, Analytics, Multi-tenant) NO INICIADAS.',
            'Cobertura: infraestructura 80% · hub central 90% · API de integración 95% · dashboard 95% · CRM Twenty 90% · automatizaciones n8n 60% · agentes IA Dify 40% · bandeja Chatwoot 0% (caído) · WhatsApp real 0% (bloqueado) · clasificación de leads 90% · documentación 100%.',
          ],
          mini_tareas: [
            { id: 'w-1', titulo: 'Diagnosticar Chatwoot (reinicio continuo)', hecha: false },
            { id: 'w-2', titulo: 'Activar workflows n8n desde la UI', hecha: false },
            { id: 'w-3', titulo: 'Verificar login Dify y workflow clasificador', hecha: false },
            { id: 'w-4', titulo: 'Integrar endpoint de subida Excel al hub', hecha: false },
          ],
        },
        {
          id: 'sec-pendientes',
          titulo: 'Pendientes priorizados (P0-P3)',
          icono: 'list_alt',
          contenido: [
            'P0: seguridad pre-deploy (S1-S3: HELPER_API_KEY literal, ELASTIC_PASSWORD en CI, secrets/PII en git history) · limpieza de secretos con filter-repo · cutover PG primario + multi-tenant (feature flag STORE_MODE=pg).',
            'P1: re-auditoría de seguridad · CI con gates · activación UI n8n · Frappe ERP diferido.',
            'P2: BI Metabase + KPIs · planes y onboarding automático · despliegue distribuido prod + piloto · cierre de gaps G-13..G-45 (~31).',
            'P3: i18n dashboard · exportar reportes · notificaciones push · CRUD usuarios/agentes · modo oscuro.',
          ],
          mini_tareas: [
            { id: 'w-5', titulo: 'Seguridad pre-deploy S1-S3 (etapa deploy)', hecha: false },
            { id: 'w-6', titulo: 'Cutover PG primario + STORE_MODE=pg', hecha: false },
            { id: 'w-7', titulo: 'CI con gates de aprobación', hecha: false },
            { id: 'w-8', titulo: 'Despliegue distribuido prod + piloto (F-54/F-56)', hecha: false },
          ],
        },
        {
          id: 'sec-roadmap',
          titulo: 'Roadmap F0-F7',
          icono: 'flag',
          contenido: [
            'F0 Fundación ✅ · F1 WhatsApp+IA+Twenty 70% · F2 Frappe ERP ⏸ · F3 Lumi Sales Copilot ⏸ · F4 Pipeline IA Avanzado ⏸ · F5 Endurecimiento Producción ⏸ · F6 Analytics ⏸ · F7 Multi-Tenant ⏸.',
            'Métricas objetivo: servicios >99.9% · helper <200ms p95 · clasificación Dify <5s · campañas >1000 msgs/h · precisión clasificación IA >85%.',
          ],
          mini_tareas: [
            { id: 'w-9', titulo: 'Configurar Meta App Business + webhook', hecha: false },
            { id: 'w-10', titulo: 'Inbox WhatsApp en Chatwoot + webhook a n8n', hecha: false },
            { id: 'w-11', titulo: 'Prueba flujo inbound y campaign broadcast', hecha: false },
            { id: 'w-12', titulo: 'Validación SSO con Authelia', hecha: false },
          ],
        },
        {
          id: 'sec-documentacion',
          titulo: 'Documentación (GitLab · 100+ docs)',
          icono: 'folder_shared',
          contenido: [
            'La documentación oficial vive en GitLab local (sales-ai-platform/wibsite). Navegación: `wibsite/INDEX.md` → capas contextual (CTX-01..07, QUÉ/POR QUÉ), técnica (TEC-01..06, CÓMO), maestro RAG (68 funcionalidades core G1-G18).',
            'Maestros estratégicos: BUSINESS (4 planes SaaS, 6 KPIs, 10 industrias), DATA (13 entidades, multi-tenant), OPS (CI/CD, monitoreo, backup/DR), SECURITY (7 críticas + roadmap hardening 5 fases), UI-UX (portal unificado), ROADMAP-MULTI-AGENT-MEMORY-CONTEXT (memoria, RAG, multimodal).',
            'Documentación verificada con suite TeVS 11/11 PASSED y 169 tests en 19 suites.',
          ],
          mini_tareas: [
            { id: 'w-13', titulo: 'Cargar Business Master (planes, KPIs, industrias)', hecha: false },
            { id: 'w-14', titulo: 'Cargar lógica del vendedor IA (CTX-04)', hecha: false },
            { id: 'w-15', titulo: 'Cargar modelo de datos (DATA-MASTER)', hecha: false },
            { id: 'w-16', titulo: 'Cargar plan de implementación TEC-06', hecha: false },
          ],
          subpaginas: [
            {
              id: 'sub-wibsite-negocio',
              titulo: 'BUSINESS-MASTER · Estrategia y monetización',
              contenido: '# Planes SaaS\n- Demo, Blue, ProMax, Enterprise (precios y márgenes).\n\n# KPIs centrales\n- 6 KPIs que miden salud del agente y del negocio.\n\n# Industrias\n- 10 industrias mapeadas con switcher de contexto por tipo de negocio (arquitectura de 3 capas: núcleo / plantilla por rubro / config por cliente).\n\n# Confidencialidad\n- Niveles public/assisted/internal para el manejo de información.\n\n> Fuente: wibsite/BUSINESS-MASTER.md (GitLab)',
              icono: 'payments',
              mini_tareas: [
                { id: 'wm-1', titulo: 'Definir precio inicial y piloto (Blue)', hecha: false },
              ],
              mapas: [],
            },
            {
              id: 'sub-wibsite-vendedor',
              titulo: 'Lógica del vendedor IA (CTX-04)',
              contenido: '# Flujo de venta\n- 8 etapas con autonomía green/yellow/red.\n- 8 objeciones con banco de respuestas.\n- Temperatura de scoring y cadencia de 8 intentos.\n- Handoff a humano (HITL) cuando corresponde.\n\n# Metodologías\n- SPICED, MEDDIC, PIPC, Bowtie, KAM.\n- Topología front/back-office y triage.\n\n# Reglas WhatsApp\n- 3 reglas de contacto por WhatsApp; 6 edge cases documentados.\n\n> Fuente: docs/contextual/CTX-04-LOGICA-VENDEDOR.md (GitLab)',
              icono: 'support_agent',
              mini_tareas: [
                { id: 'wm-2', titulo: 'Definir plantilla comercial inicial', hecha: false },
              ],
              mapas: [],
            },
          ],
        },
      ],
      mapas: [
        {
          id: 'mapa-wibsite-flujo',
          tipo: 'flujo',
          titulo: 'Flujo de datos Wibsite',
          nodos: [
            { id: 'n1', titulo: 'Canales', sub: 'WhatsApp · Messenger · Email', x: 60, y: 250 },
            { id: 'n2', titulo: 'Helper Node', sub: '~120 rutas · API', x: 300, y: 250 },
            { id: 'n3', titulo: 'n8n', sub: 'workflows inbound/broadcast', x: 540, y: 160 },
            { id: 'n4', titulo: 'Dify', sub: 'clasificador LLM', x: 540, y: 340 },
            { id: 'n5', titulo: 'Twenty CRM', sub: '10 campos custom', x: 780, y: 160 },
            { id: 'n6', titulo: 'Chatwoot', sub: 'bandeja omnicanal', x: 780, y: 340 },
            { id: 'n7', titulo: 'PostgreSQL/Redis', sub: 'multi-tenant', x: 1020, y: 250 },
          ],
          conexiones: [
            { origen: 'n1', destino: 'n2', etiqueta: 'webhooks' },
            { origen: 'n2', destino: 'n3', etiqueta: 'inbound' },
            { origen: 'n2', destino: 'n4', etiqueta: 'clasificación' },
            { origen: 'n3', destino: 'n5', etiqueta: 'sync' },
            { origen: 'n4', destino: 'n6', etiqueta: 'reply' },
            { origen: 'n2', destino: 'n7', etiqueta: 'lecturas' },
          ],
        },
      ],
    },
    // Fichas de materias (contexto por materia)
    ...(function () {
      const fichasMaterias = [
        {
          id: 'mat-ingles',
          titulo: 'Inglés Básico',
          contenido: 'Materia de idioma inglés. Horario: lunes 07:45-09:15 y viernes 07:45-09:15 (2 bloques semanales).',
        },
        {
          id: 'mat-modelamiento-bd',
          titulo: 'Modelamiento de Base de Datos',
          contenido: 'Modelado de bases de datos (entidades, relaciones, normalización). Horario: lunes 09:15-10:30 y jueves 09:15-11:30.',
        },
        {
          id: 'mat-poo',
          titulo: 'Programación Orientada a Objetos',
          contenido: 'Programación orientada a objetos: clases, herencia, polimorfismo, diseño. Horario: martes 07:45-10:30 y jueves 07:45-09:15.',
        },
        {
          id: 'mat-matematica-discreta',
          titulo: 'Matemática Discreta',
          contenido: 'Matemática discreta: lógica, conjuntos, grafos, combinatoria. Horario: miércoles 07:45-09:15 y viernes 09:15-11:30.',
        },
        {
          id: 'mat-administracion-negocios',
          titulo: 'Administración de Negocios',
          contenido: 'Administración de negocios: gestión, planificación, organizaciones. Horario: miércoles 09:15-12:15.',
        },
        {
          id: 'mat-cna',
          titulo: 'CNA 1',
          contenido: 'CNA 1 (Competencias y Nuevos Aprendizajes). Horario: sábado 07:45-11:30.',
        },
      ]
      return fichasMaterias.map((m) => ({
        id: `ficha-materia-${m.id}`,
        titulo: `Materia · ${m.titulo}`,
        subtitulo: 'Ficha de materia · Universidad',
        tipo: 'nota' as const,
        entidad_id: m.id,
        area_id: 'universidad' as const,
        estado: 'INSCRITA',
        estado_color: 'area-univ',
        propiedades: [
          { etiqueta: 'Área', valor: 'Universidad', icono: 'school' },
          { etiqueta: 'Horario', valor: m.contenido.split('Horario:')[1]?.trim() ?? '—', icono: 'schedule' },
        ],
        secciones: [
          {
            id: 'sec-contexto',
            titulo: 'Contexto',
            icono: 'info',
            contenido: [m.contenido],
            mini_tareas: [],
          },
          {
            id: 'sec-apuntes',
            titulo: 'Apuntes e investigaciones',
            icono: 'edit_note',
            contenido: ['Se cargarán apuntes, tareas, notas y observaciones según avance el semestre.'],
            mini_tareas: [],
          },
        ],
        mapas: [],
      }))
    })(),
    // Fichas freelance
    ...[
      {
        id: 'proy-ticketero',
        titulo: 'Sistema Ticketero',
        desc: 'Sistema integral de gestión de turnos para atención al cliente: tickets en kiosko físico o virtual, atención en tiempo real (SignalR/WebSockets), monitor de puestos, pantalla de llamadores, panel de administración (usuarios, áreas, servicios) y dashboard con fl_chart. Stack: .NET 8 + Flutter 3.22 + SQL Server 2022 + Redis + Docker.',
      },
      {
        id: 'proy-sistema-prestamos',
        titulo: 'Sistema de Gestión de Préstamos',
        desc: 'App de escritorio Flutter (Windows) para gestión financiera: clientes, préstamos con tabla de amortización automática, intereses (simple/compuesto), calendarios de pago, aplicación de pagos en cascada (mora → interés → capital), mora automática, control de cajas/cuentas, reportes y exportación PDF/Excel. Persistencia SQLite, arquitectura limpia SOLID, modo oscuro.',
      },
      {
        id: 'proy-billar',
        titulo: 'BillarSistem',
        desc: 'Sistema de gestión de billar con especificación técnica completa (v1.0-espec). Arquitectura local-first con sincronización híbrida. Flutter + Dart.',
      },
      {
        id: 'proy-fairplay',
        titulo: 'FairPlay Anti-Robo',
        desc: 'Sistema antirrobo UHF RFID. Demo MVP funcional (v0.1-demo): modo simulación y modo real con lector ZKTeco U2000F. Python + customtkinter.',
      },
      {
        id: 'proy-avatar13',
        titulo: 'Avatar-13',
        desc: 'Captura de movimiento de avatar en tiempo real mediante visión artificial (MediaPipe + Unity + UniVRM). 100% local, privado y seguro. v0.2.0 — en desarrollo activo.',
      },
      {
        id: 'proy-gestor-proyectos',
        titulo: 'Gestor Proyectos (AI Governance)',
        desc: 'Plataforma de gobernanza activa para proyectos asistidos por IA: adopción de workspaces con escaneo inteligente, Digital Twin, Health Baseline (6 dimensiones), ADRs, panel de actividad en tiempo real. Fastify + React + TypeScript. v0.1-alpha.',
      },
    ].map((p) => ({
      id: `ficha-${p.id}`,
      titulo: p.titulo,
      subtitulo: 'Ficha de Proyecto · Freelance',
      tipo: 'proyecto' as const,
      entidad_id: p.id,
      area_id: 'freelance' as const,
      estado: 'DOCUMENTADO · CERCANO A FINAL',
      estado_color: 'area-freelance',
      propiedades: [
        { etiqueta: 'Fuente', valor: 'GitHub · joseRobertoQuiroga', icono: 'github' },
        { etiqueta: 'Estado', valor: 'Documentado en README del repo', icono: 'flag' },
      ],
      secciones: [
        {
          id: 'sec-contexto',
          titulo: 'Contexto y detalle',
          icono: 'description',
          contenido: [p.desc],
          mini_tareas: [],
        },
        {
          id: 'sec-siguiente',
          titulo: 'Próximo análisis',
          icono: 'rocket_launch',
          contenido: ['Pendiente el cruce documentación ↔ código para el veredicto final de estado.'],
          mini_tareas: [],
        },
      ],
      mapas: [],
    })),
  ],
})

/**
 * Base vacía: la app es una aplicación de notas real, no una demo.
 * Sin datos guardados ni backend configurado, arranca sin datos inventados.
 * (El seed de arriba queda disponible como "Restaurar demo" en Configuración.)
 */
export const dbVacia = (): DB => ({
  areas: [
    { id: 'universidad', nombre: 'Universidad', icono: 'school', color: 'area-univ' },
    { id: 'freelance', nombre: 'Freelance', icono: 'business_center', color: 'area-freelance' },
    { id: 'emprendimiento', nombre: 'Emprendimiento', icono: 'lightbulb', color: 'area-emprende' },
    { id: 'personal', nombre: 'Personal', icono: 'favorite', color: 'area-personal' },
  ],
  plantillas: [
    { id: 'tpl-nota-rapida', nombre: 'Nota rápida', icono: 'bolt', color: 'area-personal', area_id: null, es_sistema: true, campos: [] },
    { id: 'tpl-materia', nombre: 'Materia universitaria', icono: 'school', color: 'area-univ', area_id: 'universidad', es_sistema: true, campos: [{ campo: 'Docente', tipo: 'texto' }, { campo: 'Semestre', tipo: 'texto' }, { campo: 'Horario', tipo: 'texto' }] },
    { id: 'tpl-proyecto', nombre: 'Proyecto', icono: 'rocket_launch', color: 'area-emprende', area_id: 'emprendimiento', es_sistema: true, campos: [{ campo: 'Stack', tipo: 'texto' }, { campo: 'Repositorio', tipo: 'texto' }] },
    { id: 'tpl-cliente', nombre: 'Cliente', icono: 'handshake', color: 'area-freelance', area_id: 'freelance', es_sistema: true, campos: [{ campo: 'Contacto', tipo: 'texto' }, { campo: 'Estado relación', tipo: 'select', opciones: ['Prospecto', 'Activo', 'Inactivo'] }] },
    { id: 'tpl-adr', nombre: 'Decisión técnica (ADR)', icono: 'account_tree', color: 'area-emprende', area_id: null, es_sistema: true, campos: [{ campo: 'Contexto', tipo: 'texto' }, { campo: 'Alternativas', tipo: 'texto' }, { campo: 'Consecuencias', tipo: 'texto' }] },
  ],
  proyectos: [],
  tareas: [],
  notas: [],
  clientes: [],
  ideas: [],
  eventos: [],
  materias: [],
  asistencias: [],
  pomodoroLog: [],
  fichas: [],
})